pipeline {
    agent {
        label 'built-in'
    }
    stages {
        stage ('install-httpd') {
            steps {
                sh "yum install httpd -y"
            }
        }
        stage ('copy-index') {
            steps {
                sh 'cp -r /vel-app/index.html /var/www/html'
            }
        }
        stage ('copy-dev') {
            steps {
                sh 'cp -r /vel-app/dev.html /var/www/html'
            }
        }
        stage ('copy-qa') {
            steps {
                sh 'cp -r /vel-app/qa.html /var/www/html'
            }
        }
        stage ('copy-uat') {
            steps {
                sh 'cp -r /vel-app/uat.html /var/www/html'
            }
        }
        stage ('restart-httpd') {
            steps {
                sh 'service httpd restart'
            }
        }
    }

}
