pipeline {
    agent {
        label 'built-in'
    }
    stages {
        stage ('install-httpd') {
            steps {
                sh "yum install httpd"
            }
        }
        stage ('copy-index') {
            steps {
                sh 'cp -r index.html /var/www/html'
            }
        }
        stage ('copy-dev') {
            steps {
                sh 'cp -r dev.html /var/www/html'
            }
        }
        stage ('copy-qa') {
            steps {
                sh 'cp -r qa.html /var/www/html'
            }
        }
        stage ('copy-uat') {
            steps {
                sh 'cp -r uat.html /var/www/html'
            }
        }
        stage ('restart-httpd') {
            steps {
                sh 'service httpd restart'
            }
        }
    }

}
